-- AlterTable
ALTER TABLE "Audi" ADD COLUMN     "cols" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "rows" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Seat" ADD COLUMN     "price" INTEGER NOT NULL DEFAULT 0;
