import type { Metadata } from "next";
import Appbar from "@/components/TempAppbar";
// import Appbar from '@repo/ui/appbar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
            <div className="h-screen z-1 bg-black overflow-y-auto">
                <Appbar />
                {children}</div>
  );
}
